/*
  WARNING: This file is automatically generated and any changes made to it will be overwritten without warning.
  Do NOT manually edit this file or your changes will be lost.
*/

import { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform } from "@marko/run/namespace";
import type * as Run from "@marko/run";


declare module "@marko/run" {
	interface AppData extends Run.DefineApp<{
		routes: {
			"/": { verb: "get"; };
			"/blog": { verb: "get"; };
			"/blog/airline-food": { verb: "get"; };
			"/bucket-list": { verb: "get"; };
			"/contact": { verb: "get"; };
			"/game": { verb: "get"; };
			"/game/reduce": { verb: "get"; };
		}
	}> {}
}

declare module "../src/routes/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/blog/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/blog"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/blog/airline-food/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/blog/airline-food"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/bucket-list/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/bucket-list"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/contact/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/contact"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/game/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/game"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/game/reduce/+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/game/reduce"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/+layout.marko" {
  export interface Input extends Run.LayoutInput<typeof import("../src/routes/+layout.marko")> {}
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/" | "/blog" | "/blog/airline-food" | "/bucket-list" | "/contact" | "/game" | "/game/reduce"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}
